#include "help.h"
#include <cstdio>
#include <cstring>
#include <string>

namespace ast
{
namespace
{

// ---------------------------------------------------------------------------
// Command metadata

enum class CommandCategory
{
    ASTInspection,
    SemanticAnalysis,
};

struct CommandEntry
{
    const char8_t*  name;
    const char8_t*  summary;
    CommandCategory category;
    const char8_t*  detail;
    bool            internal;
};

// ---------------------------------------------------------------------------
// Per-command help texts

static const char8_t kHelpDump[] =
    u8"NAME\n"
    u8"    dump - Print all AST nodes of a source file.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool dump <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print every AST node in depth-first order.\n"
    u8"    Output includes all node types, including anonymous punctuation\n"
    u8"    and keyword tokens.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file to parse.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line per AST node:\n"
    u8"\n"
    u8"        <type> <ID>\n"
    u8"\n"
    u8"    <type>    Node type string (e.g. function_definition, identifier).\n"
    u8"    <ID>      32-bit node hash in uppercase hexadecimal (e.g. 9E52E360).\n"
    u8"              Use this value with the find, parent, and children commands.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Inspect all nodes in a source file:\n"
    u8"\n"
    u8"        ast-tool dump src/main.cpp\n"
    u8"\n"
    u8"    Inspect a header file:\n"
    u8"\n"
    u8"        ast-tool dump include/parser.hpp\n"
    u8"\n"
    u8"    Collect node IDs for further inspection:\n"
    u8"\n"
    u8"        ast-tool dump src/lexer.cpp\n"
    u8"        ast-tool children --id <ID> src/lexer.cpp\n";

static const char8_t kHelpSymbols[] =
    u8"NAME\n"
    u8"    symbols - List symbols in a source file.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool symbols [--json [--pretty]] <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and extract every named semantic symbol, including\n"
    u8"    functions, methods, classes, structs, enums, variables, and\n"
    u8"    namespaces.\n"
    u8"\n"
    u8"    Each symbol is annotated with its kind, fully-qualified name,\n"
    u8"    access modifier, storage qualifiers, and a stable node ID.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file to analyze.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --json      Output results as a JSON object.\n"
    u8"    --pretty    Pretty-print the JSON output. Implies --json.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    Default (plain text), one symbol per line:\n"
    u8"\n"
    u8"        <fqn> <ID>\n"
    u8"\n"
    u8"    <fqn>    Fully-qualified name of the symbol.\n"
    u8"    <ID>     32-bit node hash in uppercase hexadecimal.\n"
    u8"\n"
    u8"    JSON fields per symbol:\n"
    u8"\n"
    u8"        kind            Symbol kind (function, class, variable, ...).\n"
    u8"        name            Unqualified symbol name.\n"
    u8"        qualified_name  Fully-qualified symbol name.\n"
    u8"        access          Access specifier (public, protected, private, unknown).\n"
    u8"        static          true if the symbol is declared static.\n"
    u8"        constexpr       true if the symbol is declared constexpr.\n"
    u8"        inline          true if the symbol is declared inline.\n"
    u8"        id              32-bit node hash in uppercase hexadecimal.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    List all symbols in a source file:\n"
    u8"\n"
    u8"        ast-tool symbols src/main.cpp\n"
    u8"\n"
    u8"    List symbols from a header file:\n"
    u8"\n"
    u8"        ast-tool symbols include/parser.hpp\n"
    u8"\n"
    u8"    Export symbols as JSON for programmatic consumption:\n"
    u8"\n"
    u8"        ast-tool symbols --json src/lexer.cpp\n"
    u8"\n"
    u8"    Export symbols as readable JSON for inspection:\n"
    u8"\n"
    u8"        ast-tool symbols --json --pretty src/main.cpp\n";

static const char8_t kHelpOutline[] =
    u8"NAME\n"
    u8"    outline - Show the structural outline of a source file.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool outline <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print all named AST nodes in a depth-indented\n"
    u8"    tree.  Anonymous punctuation and keyword tokens are omitted.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file to outline.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line per named AST node, indented by tree depth:\n"
    u8"\n"
    u8"        <indent><type>[ \"<text>\"] @<line>:<col>\n"
    u8"\n"
    u8"    <indent>  Two spaces per depth level.\n"
    u8"    <type>    Node type string.\n"
    u8"    <text>    Source text of the node, present only on leaf nodes.\n"
    u8"    <line>    1-based source line.\n"
    u8"    <col>     1-based source column.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Inspect the structure of a source file:\n"
    u8"\n"
    u8"        ast-tool outline src/main.cpp\n"
    u8"\n"
    u8"    Inspect the public interface of a header file:\n"
    u8"\n"
    u8"        ast-tool outline include/parser.hpp\n"
    u8"\n"
    u8"    Inspect a deeply nested implementation file:\n"
    u8"\n"
    u8"        ast-tool outline project/src/codegen.cpp\n";

static const char8_t kHelpFind[] =
    u8"NAME\n"
    u8"    find - Find AST nodes by type, text, position, or ID.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool find [--type <type>] [--grammar <grammar>] [--text <text>]\n"
    u8"                  [--id <hex>] [--line <n>] [--column <n>] <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print every AST node that matches all supplied\n"
    u8"    filters simultaneously.  When no filter is given, all nodes are\n"
    u8"    printed.\n"
    u8"\n"
    u8"    --line and --column must be supplied together to filter by position.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file to search.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --type <type>       Match nodes whose type equals <type>\n"
    u8"                        (e.g. function_definition, identifier).\n"
    u8"    --grammar <grammar> Match nodes whose grammar type equals <grammar>.\n"
    u8"    --text <text>       Match nodes whose source text equals <text>.\n"
    u8"    --id <hex>          Match the node with the given hash. Accepts\n"
    u8"                        uppercase or lowercase hex, with or without\n"
    u8"                        a leading 0x prefix (e.g. 9E52E360, 0x9e52e360).\n"
    u8"    --line <n>          Match nodes that start on line <n> (1-based).\n"
    u8"    --column <n>        Match nodes that start at column <n> (1-based).\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line per matching AST node:\n"
    u8"\n"
    u8"        <ID> <type> @<line>:<col>[ \"<text>\"]\n"
    u8"\n"
    u8"    <ID>      32-bit node hash in uppercase hexadecimal.\n"
    u8"    <type>    Node type string.\n"
    u8"    <line>    1-based source line.\n"
    u8"    <col>     1-based source column.\n"
    u8"    <text>    Source text of the node, present when non-empty.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find all function definitions in a file:\n"
    u8"\n"
    u8"        ast-tool find --type function_definition src/parser.cpp\n"
    u8"\n"
    u8"    Find the node at a specific cursor position:\n"
    u8"\n"
    u8"        ast-tool find --line 42 --column 17 src/parser.cpp\n"
    u8"\n"
    u8"    Find all uses of a specific identifier:\n"
    u8"\n"
    u8"        ast-tool find --type identifier --text initialize src/main.cpp\n"
    u8"\n"
    u8"    Look up a specific node by ID:\n"
    u8"\n"
    u8"        ast-tool find --id <node-id> src/main.cpp\n";

static const char8_t kHelpRange[] =
    u8"NAME\n"
    u8"    range - Show AST nodes within a source range.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool range [--start-line <n>] [--start-column <n>]\n"
    u8"                   [--end-line <n>]   [--end-column <n>]   <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print every AST node whose source span overlaps\n"
    u8"    the specified line and column range.  All options are optional;\n"
    u8"    omitted bounds default to 0.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file to search.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --start-line <n>    First line of the source range (1-based).\n"
    u8"    --start-column <n>  First column of the source range (1-based).\n"
    u8"    --end-line <n>      Last line of the source range (1-based).\n"
    u8"    --end-column <n>    Last column of the source range (1-based).\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line per matching AST node:\n"
    u8"\n"
    u8"        <ID> <type> @<line>:<col>[ \"<text>\"]\n"
    u8"\n"
    u8"    <ID>      32-bit node hash in uppercase hexadecimal.\n"
    u8"    <type>    Node type string.\n"
    u8"    <line>    1-based source line.\n"
    u8"    <col>     1-based source column.\n"
    u8"    <text>    Source text of the node, present when non-empty.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find all nodes on a single line:\n"
    u8"\n"
    u8"        ast-tool range \\\n"
    u8"            --start-line 42 --start-column 1 \\\n"
    u8"            --end-line   42 --end-column   80 \\\n"
    u8"            src/parser.cpp\n"
    u8"\n"
    u8"    Find all nodes in a block of code:\n"
    u8"\n"
    u8"        ast-tool range \\\n"
    u8"            --start-line 100 --start-column 1 \\\n"
    u8"            --end-line   150 --end-column   1 \\\n"
    u8"            src/codegen.cpp\n"
    u8"\n"
    u8"    Find the node at an exact cursor position:\n"
    u8"\n"
    u8"        ast-tool range \\\n"
    u8"            --start-line 17 --start-column 5 \\\n"
    u8"            --end-line   17 --end-column   5 \\\n"
    u8"            include/parser.hpp\n";

static const char8_t kHelpParent[] =
    u8"NAME\n"
    u8"    parent - Show the parent AST node.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool parent --id <hex> <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print the parent AST node of the node identified\n"
    u8"    by --id.  Use the dump, find, or outline commands to obtain node IDs.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --id <hex>    ID of the target node. Required. Accepts uppercase or\n"
    u8"                  lowercase hex, with or without a leading 0x prefix\n"
    u8"                  (e.g. 9E52E360, 0x9e52e360).\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line describing the parent AST node:\n"
    u8"\n"
    u8"        <ID> <type> @<line>:<col>[ \"<text>\"]\n"
    u8"\n"
    u8"    <ID>      32-bit node hash in uppercase hexadecimal.\n"
    u8"    <type>    Node type string.\n"
    u8"    <line>    1-based source line.\n"
    u8"    <col>     1-based source column.\n"
    u8"    <text>    Source text of the node, present when non-empty.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find the node at a cursor position, then walk up to its parent:\n"
    u8"\n"
    u8"        ast-tool find --line 42 --column 17 src/parser.cpp\n"
    u8"        ast-tool parent --id <node-id> src/parser.cpp\n"
    u8"\n"
    u8"    Walk up two levels to reach an enclosing declaration:\n"
    u8"\n"
    u8"        ast-tool parent --id <node-id>   src/main.cpp\n"
    u8"        ast-tool parent --id <parent-id> src/main.cpp\n";

static const char8_t kHelpChildren[] =
    u8"NAME\n"
    u8"    children - Show the child AST nodes.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool children --id <hex> <file>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Parse <file> and print all immediate child AST nodes of the node\n"
    u8"    identified by --id.  Use the dump, find, or outline commands to\n"
    u8"    obtain node IDs.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <file>    Path to the source file.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --id <hex>    ID of the target node. Required. Accepts uppercase or\n"
    u8"                  lowercase hex, with or without a leading 0x prefix\n"
    u8"                  (e.g. 9E52E360, 0x9e52e360).\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    One line per child AST node:\n"
    u8"\n"
    u8"        <ID> <type> @<line>:<col>[ \"<text>\"]\n"
    u8"\n"
    u8"    <ID>      32-bit node hash in uppercase hexadecimal.\n"
    u8"    <type>    Node type string.\n"
    u8"    <line>    1-based source line.\n"
    u8"    <col>     1-based source column.\n"
    u8"    <text>    Source text of the node, present when non-empty.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find a function definition, then list its child nodes:\n"
    u8"\n"
    u8"        ast-tool find --type function_definition src/parser.cpp\n"
    u8"        ast-tool children --id <node-id> src/parser.cpp\n"
    u8"\n"
    u8"    Inspect the children of the root node:\n"
    u8"\n"
    u8"        ast-tool dump src/main.cpp\n"
    u8"        ast-tool children --id <root-id> src/main.cpp\n";

static const char8_t kHelpSearch[] =
    u8"NAME\n"
    u8"    search - Search symbols in the workspace.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool search [--name <name>] [--fqn <fqn>] [--kind <kind>]\n"
    u8"                    [--file <path>] [--name-regex <re>] [--fqn-regex <re>]\n"
    u8"                    [--file-regex <re>] [--json [--pretty]] <root>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Scan every source file under <root>, extract semantic symbols, and\n"
    u8"    print those that match all supplied filters.  When no filter is\n"
    u8"    given, all symbols in the workspace are printed.\n"
    u8"\n"
    u8"    Exact filters and regex filters for the same field are mutually\n"
    u8"    exclusive (e.g. --name and --name-regex cannot be combined).\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <root>    Workspace root directory to scan recursively.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"  Exact filters (substring match):\n"
    u8"    --name <name>       Match symbols whose unqualified name contains <name>.\n"
    u8"    --fqn <fqn>         Match symbols whose fully-qualified name contains\n"
    u8"                        <fqn>.\n"
    u8"    --kind <kind>       Match symbols of the given kind (function, method,\n"
    u8"                        class, struct, enum, variable, ...).\n"
    u8"    --file <path>       Match symbols in files whose path contains <path>.\n"
    u8"\n"
    u8"  Regex filters (RE2 syntax):\n"
    u8"    --name-regex <re>   Match symbols whose unqualified name matches <re>.\n"
    u8"    --fqn-regex  <re>   Match symbols whose fully-qualified name matches\n"
    u8"                        <re>.\n"
    u8"    --file-regex <re>   Match symbols in files whose path matches <re>.\n"
    u8"\n"
    u8"  Output format:\n"
    u8"    --json              Output results as a JSON array.\n"
    u8"    --pretty            Pretty-print the JSON output. Implies --json.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    Default (plain text), one symbol per line:\n"
    u8"\n"
    u8"        <kind> <fqn> <file>:<line>:<col>\n"
    u8"\n"
    u8"    JSON fields per symbol:\n"
    u8"\n"
    u8"        kind            Symbol kind (function, class, variable, ...).\n"
    u8"        name            Unqualified symbol name.\n"
    u8"        fqn             Fully-qualified symbol name.\n"
    u8"        file            Path of the file that declares the symbol.\n"
    u8"        line            1-based declaration line.\n"
    u8"        column          1-based declaration column.\n"
    u8"        owning_scope    Lexical scope kind that contains the symbol.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    List all symbols in a workspace:\n"
    u8"\n"
    u8"        ast-tool search src/\n"
    u8"\n"
    u8"    Find all functions in a workspace:\n"
    u8"\n"
    u8"        ast-tool search --kind function src/\n"
    u8"\n"
    u8"    Find all symbols whose name contains 'parse':\n"
    u8"\n"
    u8"        ast-tool search --name parse src/\n"
    u8"\n"
    u8"    Find all classes declared in header files:\n"
    u8"\n"
    u8"        ast-tool search --kind class --file-regex '\\.hpp$' src/\n"
    u8"\n"
    u8"    Find all symbols in a specific namespace:\n"
    u8"\n"
    u8"        ast-tool search --fqn-regex '^ast::' src/\n"
    u8"\n"
    u8"    Export results as JSON for programmatic consumption:\n"
    u8"\n"
    u8"        ast-tool search --kind function --json --pretty src/\n";

static const char8_t kHelpCallees[] =
    u8"NAME\n"
    u8"    callees - Find direct callees of a function.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool callees [--json [--pretty]] <symbol> <root>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Analyze the workspace rooted at <root>, resolve the named function\n"
    u8"    symbol, and print every function directly called from within that\n"
    u8"    function's body.\n"
    u8"\n"
    u8"    Only direct calls resolvable by the semantic resolver are reported.\n"
    u8"    Indirect calls through function pointers or virtual dispatch are not\n"
    u8"    included.  Transitive (indirect) callee analysis is not performed.\n"
    u8"\n"
    u8"    If <symbol> contains '::' it is matched against fully-qualified names;\n"
    u8"    otherwise it is matched against unqualified names.  If the query matches\n"
    u8"    more than one symbol the command fails with a list of candidates;\n"
    u8"    supply a fully-qualified name to disambiguate.\n"
    u8"\n"
    u8"    The target must be a function, method, constructor, or destructor.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <symbol>  Symbol name or fully-qualified name to look up.\n"
    u8"    <root>    Workspace root directory to scan recursively.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --json      Output results as a JSON array.\n"
    u8"    --pretty    Pretty-print the JSON output. Implies --json.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    Default (plain text), one call site per line:\n"
    u8"\n"
    u8"        <callee_fqn> <file>:<line>:<col>\n"
    u8"\n"
    u8"    <callee_fqn>  Fully-qualified name of the called function.\n"
    u8"    <file>        Path of the file containing the call.\n"
    u8"    <line>        1-based source line of the call.\n"
    u8"    <col>         1-based source column of the call.\n"
    u8"\n"
    u8"    JSON fields per call site:\n"
    u8"\n"
    u8"        callee_kind   Kind of the called symbol (function, method, ...).\n"
    u8"        callee_fqn    Fully-qualified name of the called function.\n"
    u8"        file          Path of the file containing the call.\n"
    u8"        line          1-based source line of the call.\n"
    u8"        column        1-based source column of the call.\n"
    u8"\n"
    u8"    Output is sorted by file, then by line and column, then by callee FQN.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find all functions directly called by 'process':\n"
    u8"\n"
    u8"        ast-tool callees process src/\n"
    u8"\n"
    u8"    Find callees of a fully-qualified name to disambiguate:\n"
    u8"\n"
    u8"        ast-tool callees ast::process src/\n"
    u8"\n"
    u8"    Export results as JSON for programmatic consumption:\n"
    u8"\n"
    u8"        ast-tool callees --json --pretty foo src/\n";

static const char8_t kHelpCallers[] =
    u8"NAME\n"
    u8"    callers - Find direct callers of a function.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool callers [--json [--pretty]] <symbol> <root>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Analyze the workspace rooted at <root>, resolve the named function\n"
    u8"    symbol, and print every call site in the workspace where that function\n"
    u8"    is directly called.\n"
    u8"\n"
    u8"    Only direct calls resolvable by the semantic resolver are reported.\n"
    u8"    Indirect calls through function pointers or virtual dispatch are not\n"
    u8"    included.  Transitive (indirect) caller analysis is not performed.\n"
    u8"\n"
    u8"    If <symbol> contains '::' it is matched against fully-qualified names;\n"
    u8"    otherwise it is matched against unqualified names.  If the query matches\n"
    u8"    more than one symbol the command fails with a list of candidates;\n"
    u8"    supply a fully-qualified name to disambiguate.\n"
    u8"\n"
    u8"    The target must be a function, method, constructor, or destructor.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <symbol>  Symbol name or fully-qualified name to look up.\n"
    u8"    <root>    Workspace root directory to scan recursively.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --json      Output results as a JSON array.\n"
    u8"    --pretty    Pretty-print the JSON output. Implies --json.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    Default (plain text), one call site per line:\n"
    u8"\n"
    u8"        <caller_fqn> <file>:<line>:<col>\n"
    u8"\n"
    u8"    <caller_fqn>  Fully-qualified name of the calling function,\n"
    u8"                  or <file_scope> if the call is at file scope.\n"
    u8"    <file>        Path of the file containing the call.\n"
    u8"    <line>        1-based source line of the call.\n"
    u8"    <col>         1-based source column of the call.\n"
    u8"\n"
    u8"    JSON fields per call site:\n"
    u8"\n"
    u8"        caller_kind   Kind of the calling symbol (function, method, ...).\n"
    u8"        caller_fqn    Fully-qualified name of the calling function.\n"
    u8"        file          Path of the file containing the call.\n"
    u8"        line          1-based source line of the call.\n"
    u8"        column        1-based source column of the call.\n"
    u8"\n"
    u8"    Output is sorted by file, then by caller FQN, then by line and column.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find all direct callers of a function named 'parse':\n"
    u8"\n"
    u8"        ast-tool callers parse src/\n"
    u8"\n"
    u8"    Find callers of a fully-qualified name to disambiguate:\n"
    u8"\n"
    u8"        ast-tool callers ast::parse src/\n"
    u8"\n"
    u8"    Export results as JSON for programmatic consumption:\n"
    u8"\n"
    u8"        ast-tool callers --json --pretty foo src/\n";

static const char8_t kHelpReferences[] =
    u8"NAME\n"
    u8"    references - Find references to a symbol.\n"
    u8"\n"
    u8"SYNOPSIS\n"
    u8"    ast-tool references [--json [--pretty]] <symbol> <root>\n"
    u8"\n"
    u8"DESCRIPTION\n"
    u8"    Analyze the workspace rooted at <root>, resolve the named symbol, and\n"
    u8"    print every location in the workspace where that symbol is referenced.\n"
    u8"\n"
    u8"    Resolution is semantic, not textual: identifiers are resolved via the\n"
    u8"    workspace symbol table, so only genuine uses of the target declaration\n"
    u8"    are reported.  Textual grep matches are not included.\n"
    u8"\n"
    u8"    If <symbol> contains '::' it is matched against fully-qualified names;\n"
    u8"    otherwise it is matched against unqualified names.  If the query matches\n"
    u8"    more than one declaration the command fails with a list of candidates;\n"
    u8"    supply a fully-qualified name to disambiguate.\n"
    u8"\n"
    u8"    The declaration site is excluded from results by default.\n"
    u8"\n"
    u8"ARGUMENTS\n"
    u8"    <symbol>  Symbol name or fully-qualified name to look up.\n"
    u8"    <root>    Workspace root directory to scan recursively.\n"
    u8"\n"
    u8"OPTIONS\n"
    u8"    --json      Output results as a JSON array.\n"
    u8"    --pretty    Pretty-print the JSON output. Implies --json.\n"
    u8"\n"
    u8"OUTPUT\n"
    u8"    Default (plain text), one reference per line:\n"
    u8"\n"
    u8"        <file>:<line>:<col>\n"
    u8"\n"
    u8"    <file>    Path of the file containing the reference.\n"
    u8"    <line>    1-based source line of the reference.\n"
    u8"    <col>     1-based source column of the reference.\n"
    u8"\n"
    u8"    JSON fields per reference:\n"
    u8"\n"
    u8"        file            Path of the file containing the reference.\n"
    u8"        line            1-based source line of the reference.\n"
    u8"        column          1-based source column of the reference.\n"
    u8"        owning_scope    Lexical scope kind that encloses the reference.\n"
    u8"\n"
    u8"    Output is sorted by file, then by line, then by column.\n"
    u8"\n"
    u8"EXAMPLES\n"
    u8"    Find all references to a function named 'parse':\n"
    u8"\n"
    u8"        ast-tool references parse src/\n"
    u8"\n"
    u8"    Find references to a fully-qualified name to disambiguate:\n"
    u8"\n"
    u8"        ast-tool references ast::parse src/\n"
    u8"\n"
    u8"    Export results as JSON for programmatic consumption:\n"
    u8"\n"
    u8"        ast-tool references --json --pretty foo src/\n";

// ---------------------------------------------------------------------------
// Command metadata tables

static const CommandEntry kCommands[] = {
    // AST Inspection (internal)
    {u8"dump",     u8"Print all AST nodes of a source file.",              CommandCategory::ASTInspection,   kHelpDump,     true},
    // AST Inspection (public)
    {u8"outline",  u8"Show the structural outline of a source file.",      CommandCategory::ASTInspection,   kHelpOutline,  false},
    {u8"find",     u8"Find AST nodes by type, text, position, or ID.",     CommandCategory::ASTInspection,   kHelpFind,     false},
    {u8"range",    u8"Show AST nodes within a source range.",              CommandCategory::ASTInspection,   kHelpRange,    false},
    {u8"parent",   u8"Show the parent AST node.",                          CommandCategory::ASTInspection,   kHelpParent,   false},
    {u8"children", u8"Show the child AST nodes.",                          CommandCategory::ASTInspection,   kHelpChildren, false},
    // Semantic Analysis
    {u8"symbols",    u8"List symbols in a source file.",                   CommandCategory::SemanticAnalysis, kHelpSymbols,    false},
    {u8"search",     u8"Search symbols in the workspace.",                 CommandCategory::SemanticAnalysis, kHelpSearch,     false},
    {u8"references", u8"Find references to a symbol.",                     CommandCategory::SemanticAnalysis, kHelpReferences, false},
    {u8"callers",    u8"Find direct callers of a function.",               CommandCategory::SemanticAnalysis, kHelpCallers,    false},
    {u8"callees",    u8"Find direct callees of a function.",               CommandCategory::SemanticAnalysis, kHelpCallees,    false},
};

static constexpr int kCommandCount = sizeof(kCommands) / sizeof(kCommands[0]);

struct CategoryInfo
{
    CommandCategory id;
    const char*     label;
};

static const CategoryInfo kCategories[] = {
    {CommandCategory::ASTInspection,   "AST Inspection"},
    {CommandCategory::SemanticAnalysis, "Semantic Analysis"},
};

static constexpr int kCategoryCount = sizeof(kCategories) / sizeof(kCategories[0]);

} // namespace

// ---------------------------------------------------------------------------

void print_top_level_help()
{
    fputs(
        "ast-tool — Source code inspection and semantic analysis.\n"
        "\n"
        "Inspect AST structure, extract semantic symbols, and trace cross-file\n"
        "symbol relationships (references, callers, callees) across a workspace.\n"
        "\n"
        "Usage:\n"
        "    ast-tool <command> [options]\n"
        "\n"
        "Options:\n"
        "    -h, --help    Show this help message.\n"
        "\n"
        "Commands:\n",
        stdout);

    for(int ci = 0; ci < kCategoryCount; ++ci) {
        bool header_printed = false;
        for(int i = 0; i < kCommandCount; ++i) {
            if(kCommands[i].category != kCategories[ci].id) continue;
            if(kCommands[i].internal) continue;
            if(!header_printed) {
                fprintf(stdout, "\n  %s\n", kCategories[ci].label);
                header_printed = true;
            }
            fprintf(stdout, "    %-12s%s\n", (const char*)kCommands[i].name, (const char*)kCommands[i].summary);
        }
    }

    fputs(
        "\n"
        "Run:\n"
        "\n"
        "    ast-tool help <command>\n"
        "    ast-tool <command> --help\n"
        "\n"
        "for detailed documentation of a command.\n",
        stdout);
}

void print_command_help(const char8_t* topic)
{
    if(!topic) {
        print_top_level_help();
        return;
    }
    std::u8string_view topic_view{topic};
    for(int i = 0; i < kCommandCount; ++i) {
        if(topic_view == kCommands[i].name){
            fputs((const char*)kCommands[i].detail, stdout);
            return;
        }
    }
    fprintf(stderr, "error: unknown help topic '%s'\n", (const char*)topic);
    fprintf(stderr, "Run 'ast-tool help' to see available commands.\n");
}

} // namespace ast
